apache/pulsar-client-node

- .clang-format
- .eslintrc.json
- .gitignore
- Gruntfile.js
- README.md
- binding.gyp
- examples/consumer.js
- examples/producer.js
- index.js
- package-lock.json
- package.json
- perf/perf_consumer.js
- perf/perf_producer.js
- src/Client.cc
- src/Client.h
- src/Consumer.cc
- src/Consumer.h
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- src/Message.cc
- src/Message.h
- src/MessageId.cc
- src/MessageId.h
- src/Producer.cc
- src/Producer.h
- src/ProducerConfig.cc
- src/ProducerConfig.h
- src/addon.cc
- Make it easier for Nodejs users to develop apps by using Pulsar.
Node client library implemented on C++ client library wrapped by [N-API](https://github.com/nodejs/node-addon-api).
This PR implements **producer/consumer** as a minimum of function by using N-API.
We'll add future tasks (Reader, Authentication, Test, CI/CD and so on) to ISSUE.
Authors: @k2la, @hrsakai, @massakam, @yumochiz, @nkurihar
> Provide Node Client Library

- binding.gyp
- examples/consumer_tls_auth.js
- examples/producer_tls_auth.js
- index.js
- src/Authentication.cc
- src/Authentication.h
- src/AuthenticationAthenz.js
- src/AuthenticationTls.js
- src/AuthenticationToken.js
- src/Client.cc
Enable the Node.js client to use TLS, Athenz and Token authentication.
This fixes #3
> [Issue 3] Support authentication

- .eslintrc.json
- package-lock.json
- package.json
- tests/consumer.test.js
- tests/end_to_end.test.js
- tests/producer.test.js
- Install [Jest](https://jestjs.io/) Test Framework
- Add test command
- By using `$ npm test`, test starts.
- Add Tests
- producer
- error handling about `create`
- consumer
- error handling about `create`
- end-to-end
-  produce/consume
Tests are executed as follows:
```
$ npm test
> pulsar-client@2.4.0-SNAPSHOT test /home/k2la/pulsar-client-node
> jest --verbose
PASS  tests/producer.test.js
Producer
Create
✓ No Topic (8ms)
✓ Not String Topic (1ms)
✓ Not Exist Tenant (10ms)
✓ Not Exist Namespace (4ms)
PASS  tests/consumer.test.js
Consumer
Create
✓ No Topic (10ms)
✓ Not String Topic (1ms)
✓ No Subscription (1ms)
✓ Not String Subscription (2ms)
✓ Not Exist Tenant (54ms)
✓ Not Exist Namespace (5ms)
PASS  tests/end_to_end.test.js
End To End
✓ Produce/Consume (128ms)
Test Suites: 3 passed, 3 …
```
> Add Producer/Consumer/EndToEnd Tests

- pulsar-test-service-start.sh
- run-unit-tests.sh
- src/Consumer.cc
- src/Consumer.h
- tests/end_to_end.test.js
* Add acknowledgeCumulative / receiveWithTimeout methods
* Change pulsar pkg download url from `www.apache.org` to `archive.apache.org`(Older versions of package do not appear to exist on `www.apache.org`)
>  Add acknowledgeCumulative / receiveWithTimeout methods

- src/Consumer.cc
- src/Consumer.h
- tests/end_to_end.test.js
Change Interface to same as `java / cpp client`.
> Merge ReceiveWithTimeout into Receive

- tests/end_to_end.test.js
> Fix TopicName in e2e Tests.

- examples/consumer.js
- examples/consumer_tls_auth.js
- Add subscriptionType to examples.(https://github.com/apache/pulsar-client-node/issues/32)
> Add subscription type to examples.

- README.md
just changing the README so that others don't run into the same problem I did.
> added note for pulsar-client-dev rather than pulsar-client

- package-lock.json
- package.json
I have already created `branch-0.0` to perform the first release, so I will bump the master version to `0.1.0-rc.0`.
> Bump the master version to 0.1.0

- .eslintignore
- README.md
- examples/consumer.js
- examples/consumer_tls_auth.js
- examples/producer.js
- examples/producer_tls_auth.js
- examples/reader.js
- Changed examples require.
- Added installation chapter and examples chapter to readme.
> fixed readme and examples

- package-lock.json
- package.json
I have already created `branch-1.0` to perform the first release, so I will bump the master version to `1.1.0-rc.0`.
> Bump the master version to 1.1.0

- src/Consumer.cc
- src/Consumer.h
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- tests/consumer.test.js
- tests/end_to_end.test.js
Wraps negative acknowledgement functionality from the C++ library. Closes #57
> Add negative acknowledgement support for consumer

- README.md
Updated the compatibility table with C++ client in README.md.
The master code uses `pulsar_consumer_negative_acknowledge()` and `pulsar_consumer_negative_acknowledge_id()`, so a C++ client version 2.4.0 or later is required.
> Update compatibility table with C++ client

- package-lock.json
- package.json
I have already created `branch-1.1` to perform the first release, so I will bump the master version to `1.2.0-rc.0`.
> Bump the master version to 1.2.0

- index.js
Add log level definition for log function.
```
const Pulsar = require('pulsar-client');
.
.
serviceUrl: 'pulsar://localhost:6650',
log: function(level, file, line, message) {
switch(level) {
case Pulsar.LogLevel.DEBUG:
logger.debug(XXXX);
break;
case Pulsar.LogLevel.INFO:
logger.info(XXXX);
break;
case Pulsar.LogLevel.ERROR:
logger.error(XXXX);
default:
// do something
}
}
});
```
> Add log level definition

- package-lock.json
- package.json
I have already created `branch-1.2` to perform the release, so I will bump the master version to `1.3.0-rc.0`.
> Bump the master version to 1.3.0

- .github/workflows/nodejs.yml
Use github actions for precommit job.
> Add github actions

- package-lock.json
- package.json
- src/Consumer.cc
- src/Consumer.h
- tests/end_to_end.test.js
Unsubscribe was added to consumer using pulsar_consumer_unsubscribe. A version bump was also done to the latest packages, as they were out of date.
This was done to handle the request here: https://github.com/apache/pulsar-client-node/issues/105#issue-656654912
> Adds the unsubscribe() method to consumer & Bumps Versions

- README.md
- index.d.ts
- package-lock.json
- package.json
- run-unit-tests.sh
- tsconfig.json
- tslint.json
- tstest.ts
Added the type definition file for `pulsar-client`. This makes `pulsar-client` available in TypeScript.
> Add type definitions

- README.md
I'm planning to release version 1.3.0 of pulsar-client-node. In preparation for that, updated the compatibility table written in README.md.
> Updated compatibility table in README.md

- package-lock.json
- package.json
I have already created `branch-1.3` to perform the release, so I will bump the master version to `1.4.0-rc.0`.
> Bump the master version to 1.4.0

- index.d.ts
- tstest.ts
As some new properties have been added in https://github.com/apache/pulsar-client-node/pull/138, updated the type definition file for TypeScript.
> Add type definitions for properties related to E2E encryption

- index.d.ts
- tstest.ts
Added the type definition of the `disableReplication` property added in https://github.com/apache/pulsar-client-node/pull/149.
> Add type definition for disableReplication property

- index.d.ts
- tstest.ts
Add reader listener type and check whether it can be used in `tstest.ts`.
ReaderListener: https://github.com/apache/pulsar-client-node/pull/153
> Add Reader Listener Type

- index.d.ts
- tstest.ts
Add orderingKey type and check whether it can be used in `tstest.ts`.
orderingKey: https://github.com/apache/pulsar-client-node/pull/155
> Add OrderingKey Type

- package-lock.json
- package.json
I have already created branch-1.4 to perform the release, so I will bump the master version to 1.5.0-rc.0.
> Bump the master version to 1.5.0

- .eslintrc.json
- package-lock.json
- package.json
- tests/consumer.test.js
- tests/producer.test.js
- tests/reader.test.js
Cherry-picked 2 patches to branch-1.3 for backport:
* https://github.com/apache/pulsar-client-node/pull/156
* https://github.com/apache/pulsar-client-node/pull/166
> Cherry pick some patches to 1.3

- package-lock.json
- package.json
- tslint.json
Applied the same changes to https://github.com/apache/pulsar-client-node/pull/172 to branch-1.3.
> Update library with security vulnerabilities (v1.3)

- README.md
Update compatibility between nodejs client and cpp client versions for patch version.
> Fix compatibility between nodejs client and cpp client versions

- README.md
Update compatibility between nodejs client and cpp client versions for patch version.
> Fix compatibility between nodejs client and cpp client versions(v1.3)

- src/Consumer.cc
> fix: use pause and resume api to ensure orderly init listener->consumer

- README.md
Added v1.5.x of the Node.js client to the table in `README.md`.
> Add v1.5.x to the table in README

- package-lock.json
- package.json
I have already created branch-1.5 to perform the release, so bump the master version to 1.6.0-rc.0.
> Bump the master version to 1.6.0

- README.md
- binding.gyp
* Support for specified architectures
> Fixed windows install client

- README.md
- binding.gyp
* Fixed pulsar client node install script on mac
* Update readme doc
> Fixed pulsar client node mac install script

- README.md
Updated the compatibility table in README.md as version 1.6.2 has been released.
> Update compatibility table in README

- .gitignore
- binding.gyp
- index.d.ts
- package-lock.json
- package.json
- src/Client.cc
- src/Client.h
- src/Consumer.cc
- src/Consumer.h
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- src/Message.cc
- src/Message.h
- src/MessageId.cc
- src/MessageId.h
- src/MessageListener.h
- src/Producer.cc
- src/Producer.h
- src/ProducerConfig.cc
- src/ProducerConfig.h
- src/Reader.cc
- src/Reader.h
- src/ReaderConfig.cc
- src/ReaderConfig.h
- src/ReaderListener.h
- src/ThreadSafeDeferred.cc
- src/ThreadSafeDeferred.h
- tests/end_to_end.test.js
I have replaced the use of async workers with direct async functions by utilising a thread safe deferred (promise). The need for this comes from the fact that with workers, calling producer.send in order results in non-deterministic ordering, and awaiting every send would diminish the utility of having a batched mode. I also found that closing the client while worker threads were ready to execute resulted in segfaults, so this change ensures that most operations execute in the order they are called on the js side.
I've also found several places lacking in good memory management discipline and have patched a few leaks. I've opted to use shared pointers with custom destructors to wrap all of the returned pointers, referring the pulsar library code to check who owns these pointers. (I did …
> convert worker threads to async functions

- README.md
Add installation instructions on linux to README
> Add installation instructions on linux

- build-support/install-cpp-client.sh
- package.json
- pkg/mac/build-cpp-lib.sh
Since it's now available, fetch the official binaries for the CPP client 3.0.0
> Fetch C++ client official release

- index.d.ts
- src/Consumer.cc
- src/Consumer.h
- tests/end_to_end.test.js
Add seek by message id method to the consumer.
> [feat] Add support for seek by message id

- src/Consumer.cc
Related to: https://github.com/apache/pulsar-client-node/pull/200
We can't implement the receive method by async function in https://github.com/apache/pulsar-client-node/pull/200 because the cpp library didn't expose the async receive C function.
The async receive C function was implemented in https://github.com/apache/pulsar/pull/17452 . It was released in v3.0.0. So, we want to use it.
* Use `pulsar_consumer_receive_async` on Consumer#receive method
- ~Use `PULSAR_VERSION` to provide backward compatibility between other cpp clients~
Because this PR doesn't introduce new features.
> [improve][client] Use async C function in the Consumer#receive method

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci-build-release-napi.yml
- docs/release-process.md
- package.json
- src/pulsar-binding.js
Added license headers to some files by executing `npm run license:addheader`.
> Add license headers

- package-lock.json
- package.json
Bump the master version to 1.9.0-rc.0
> Bump the master version to 1.9.0

- docs/release-process.md
Update the release process.
Discussion: https://lists.apache.org/thread/dx0tzc72t3tjktmcw5xn69krmq2gvo2c
* Move release note writing after the vote finished
* Add section `Publish the release candidate to the npm`
* Add release note update for the pulsar-site
* Update the release candidate email template
* Change the release candidate folder to `pulsar-client-node-1.X.0-rc.1`
* Improve some minor points
> Update the release process

- NOTICE
Apache project needs to include a `NOTICE` file, refer: https://infra.apache.org/licensing-howto.html#mod-notice
- Add NOTICE file.
- NONE
> Add NOTICE file.

- .github/workflows/ci-pr-validation.yml
If we don't update the brew, the CI may install the old version of CPP lib and cause the CI to be failed like this:
https://github.com/apache/pulsar-client-node/actions/runs/5016662858/jobs/9000623283?pr=326#step:4:26
* Update the brew in CI
> [fix] Always update brew in CI

- index.d.ts
- src/ConsumerConfig.cc
- tests/conf/standalone.conf
- tests/consumer.test.js
#273 
- Expose batch index ack option.
- Add batch index ack unit test to cover it.
> feat: support batch index ack.

- index.d.ts
- src/ConsumerConfig.cc
- tests/consumer.test.js
Master Issue: #201 
Support dead letter topic.
- Add dead letter policy config.
- Add dead letter unit test to cover it.
> feat: Support dead letter topic.

- package-lock.json
- package.json
Bump the master version to 1.10.0
> Bump the master version to 1.10.0

- pulsar-client-cpp.txt
https://github.com/apache/pulsar-client-cpp/releases/tag/v3.4.2
Bump cpp client version to 3.4.2
- None
> Bump cpp client version to 3.4.2

- package-lock.json
- package.json
Bump the master version to 1.11.0
> Bump the master version to 1.11.0

- package-lock.json
- package.json
Bump the master version to 1.12.0
Bump the master version to 1.12.0
> Bump the master version to 1.12.0

- package-lock.json
- package.json
Bump the master version to 1.13.0 
Bump the master version to 1.13.0 
> Bump the master version to 1.13.0 

- examples/consumer-schema.js
- examples/producer-schema.js
#272
- add schema producer and consumer example
> add schema producer and consumer example

- package-lock.json
- package.json
bump master version 1.14.0-rc.0
> bump master version to 1.14.0-rc.0

- package-lock.json
- package.json
Bump master version to v1.15.0-rc.0
> Bump master version to v1.15.0-rc.0
