apache/pulsar-client-node

- examples/producer.js
- package-lock.json
- perf/perf_producer.js
- src/Producer.cc
- src/Producer.h
Exposed producer's flush method to node.js.
This eliminates the need to wait for messages to be sent using `Promise.all()`.
This fixes #2
> [Issue 2] Support Producer.flush()

- package-lock.json
- package.json
When running `npm install`, the following warning is displayed:
```
found 2 moderate severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
```
So I ran `npm audit fix` to update dependent modules.
> Update module with severity vulnerabilities

- package-lock.json
upgrade js-yaml from `3.13.0` to `3.13.1`.
`tar` package also has security vulnerability, but the latest version of `node-gyp` package(requires `tar` package) still uses a version of `tar` includes security vulnerability.
```
$ npm audit
=== npm audit security report ===
High            Code Injection
Package         js-yaml
Dependency of   eslint [dev]
Path            eslint > js-yaml
More info       https://nodesecurity.io/advisories/813
High            Code Injection
Package         js-yaml
Dependency of   grunt [dev]
Path            grunt > js-yaml
More info       https://nodesecurity.io/advisories/813
High            Code Injection
Package         js-yaml
Dependency of   jest [dev]
Path            jest > jest-cli > @jest/core > @jest/reporters >
istanbul-api > js-yaml
More info …
```
> Upgrade js-yaml to fix security vulnerability

- src/MessageId.cc
- src/MessageId.h
To restore Reader from the custom message needs to provide startMessageId
```js
const msg = await reader.readNext();
const msgId = msg.getMessageId().serialize() // native Buffer
msgId.toString("hex") // returns "085a10002000" as binary string
```
The cursor can be restored from binary string
```js
const msgId = Buffer.from("085a10002000", "hex")
const reader = await client.createReader({
startMessageId: Pulsar.MessageId.deserialize(msgId)
});
```
> added serialize/deserialize methods to set custom startMessageId in createReader 

- package.json
Library ```pulsar-client-cpp``` still needs to be installed in OS manually but it helps to install the package via npm from github/npm registry 
```sh
npm i apache/pulsar-client-node#master #from github
npm i pulsar-client #from npm registry
```
The package is ready to be published to npm registry via command
```sh
npm publish
```
> added node-pre-gyp support

- src/MessageId.cc
- src/MessageId.h
It seems that [the issue](https://github.com/apache/pulsar-client-node/issues/39) occurs when gc releases `earliest(latest) messageId`.
These messageIds shouldn't be released.
In go client library, it doesn't call `pulsar_message_id_free()` if messageid is earliest or latest.
https://github.com/apache/pulsar/blob/d5036eaefcba42e6c9d159ffb14bee597d13380f/pulsar-client-go/pulsar/c_message.go#L198-L206
https://github.com/apache/pulsar/blob/d5036eaefcba42e6c9d159ffb14bee597d13380f/pulsar-client-go/pulsar/c_message.go#L169-L177
> [Issue #39]Add skip flag for cMessageId free

- src/Client.cc
```pulsar-client-cpp/include/pulsar/ClientConfiguration.h```
```cpp
/*
* Initialize stats interval in seconds. Stats are printed and reset after every 'statsIntervalInSeconds'.
* Set to 0 in order to disable stats collection.
*/
ClientConfiguration& setStatsIntervalInSeconds(const unsigned int&);
```
By default it is 10 minutes, to disable stats log needs to be 0
> statsIntervalInSeconds can be 0 to disable log

- src/MessageId.cc
- src/ReaderConfig.h
Fixed the following warnings when compiling C++ source.
```
In file included from ../src/ReaderConfig.cc:20:0:
../src/ReaderConfig.h: In constructor 'ReaderConfig::ReaderConfig(const Napi::Object&)':
../src/ReaderConfig.h:39:15: warning: 'ReaderConfig::topic' will be initialized after [-Wreorder]
std::string topic;
^
../src/ReaderConfig.h:38:24: warning:   'pulsar_message_id_t* ReaderConfig::cStartMessageId' [-Wreorder]
pulsar_message_id_t *cStartMessageId;
^
../src/ReaderConfig.cc:30:1: warning:   when initialized here [-Wreorder]
ReaderConfig::ReaderConfig(const Napi::Object &readerConfig) : topic(""), cStartMessageId(NULL) {
^
SOLINK_MODULE(target) Release/obj.target/Pulsar.node
COPY Release/Pulsar.node
make: Leaving directory `/home/massakam/github/pulsar-client-node/build'
```
> Fix compilation warning

- .clang-format
- .eslintignore
- .gitignore
- license-header.txt
- package-lock.json
- package.json
- tests/end_to_end.test.js
I introduced `license-check-and-add` module. This module checks if the source files in the repository contain ASF's license header and adds it if not.
Usage:
```sh
$ npm run license:addheader
> pulsar-client@2.4.0-SNAPSHOT license:addheader /home/massakam/github/pulsar-client-node
> license-check-and-add
Running using exclude exact_paths list
Running using exclude file type list
Automatically adding licenses
Trailing whitespace will not be accepted in checking
Trailing whitespace will be removed from inserted licenses
? All files have licenses.
```
> Introduce license-check-and-add module

- README.md
- package-lock.json
- package.json
Set the first release version of this library to 0.0.1.
I don't think the version of the Node.js client needs to match the C++ client. The current version is 2.4.0-SNAPSHOT, but this library does not support all the features that the C++ client 2.4.0 has.
I think that independent versioning has the advantage that it can determine the release timing flexibly.
cf.
- https://gist.github.com/k2la/6de068df6b55b648fd2a9e995eb62561
- https://github.com/apache/pulsar-client-node/wiki/Release-process
> Change initial version to 0.0.1

- README.md
- package-lock.json
- package.json
Initially, I was planning to make the first release version 0.0.1 (https://github.com/apache/pulsar-client-node/pull/48), but there is an opinion that it should be 1.0.0, so I will change the version.
> Change first release version to 1.0.0

- package-lock.json
- package.json
- src/Consumer.cc
- src/Consumer.h
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- src/MessageId.cc
- src/MessageId.h
- tests/end_to_end.test.js
Adds support for a listener function to the Consumer, using the C++ client listener support.
Using `Receive` currently will block a thread from the Node worker poll. If enough consumers are waiting to receive messages from pulsar at the same time, this will completely clog the worker poll.
Since #14, `node-addon-api` has added support for `ThreadSafeFunction`'s, allowing callbacks to be made from native threads. This pull request updates the `node-addon-api` dependency version to use this, but that will increase the minimum supported node version.
This paves the way to use the async functions from the pulsar C++ client properly.
> Add listener support for consumer

- package-lock.json
Currently, when I clone this repository and run `npm install`, I get the following warning:
```
found 5 vulnerabilities (1 moderate, 4 high)
run `npm audit fix` to fix them, or `npm audit` for details
```
There seems to be multiple vulnerabilities in the library named `handlebars`, so I ran `npm audit fix` to update that version.
> Update library with security vulnerabilities

- src/ConsumerConfig.cc
- tests/end_to_end.test.js
This PR allows users to specify the initial position of the subscription when creating a consumer.
Usage:
```js
const consumer = await client.subscribe({
topic: 'persistent://public/default/t1',
subscription: 'sub1',
subscriptionInitialPosition: 'Earliest', // 'Latest' or 'Earliest'
});
```
fixes #60
> Support subscriptionInitialPosition setting

- src/Message.cc
This PR enables `pulsar_message_set_replication_clusters` setting.
fixes #18
> Support Set Replication Clusters

- .eslintrc.json
- package-lock.json
- package.json
- run-unit-tests.sh
Just before the unit tests are run by Jenkins, check the format of the code. If the format is incorrect, the job will fail.
In addition, right now, the following warnings are output when running `npm run lint`.
```
/home/massakam/github/pulsar-client-node/tests/end_to_end.test.js
59:21  warning  Unexpected `await` inside a loop  no-await-in-loop
203:21  warning  Unexpected `await` inside a loop  no-await-in-loop
269:29  warning  Unexpected `await` inside a loop  no-await-in-loop
274:29  warning  Unexpected `await` inside a loop  no-await-in-loop
322:21  warning  Unexpected `await` inside a loop  no-await-in-loop
? 5 problems (0 errors, 5 warnings)
```
These warnings can be ignored in the test code, so I modified `.eslintrc.json`.
> Check code format before unit tests

- src/Client.cc
- src/Client.h
Issue: https://github.com/apache/pulsar-client-node/issues/9
```
var client = new Pulsar.Client({
log: function(level /* typescript enum */, file, line, message) {
// log with console.log or other logging implementation
}
})
```
If no log function is passed, it will use default logging.
I am new to NAPI and C++, I am open for feedback and to learn!
> Add support for passing `log` function when creating client

- src/Client.cc
Since we don’t have reference for the client, v8 can garbage collect this instance, which can cause the next code:
```
const Pulsar = require('pulsar-client');
(async () => {
// Create a client
serviceUrl: 'pulsar://localhost:6650'
});
// Create a producer
const producer = await client.createProducer({
sendTimeoutMs: 30000,
batchingEnabled: true,
});
let i =0;
async function produceMessage() {
i = i + 1;
const msg = `my-message-${i}`;
const ret = await producer.send({
data: Buffer.from(msg),
});
console.log(`Sent message: ${msg}`);
console.log(ret);
setTimeout(produceMessage, 1000);
}
produceMessage();
})();
```
To close the connection suddenly and fail the producer.
Fixes: …
> Create reference for client

- src/Consumer.cc
- src/Consumer.h
- src/ConsumerConfig.cc
- src/MessageListener.h
This PR:
- Moves message listener to consumer
- Use a single consumer instance
**Reproduction steps:**
1. Run this code
```javascript
const Pulsar = require('pulsar-client');
(async () => {
// Create a client
serviceUrl: 'pulsar://localhost:6650'
});
// Create a consumer
const consumer = await client.subscribe({
subscription: 'sub1',
subscriptionType: 'Shared',
ackTimeoutMs: 10000,
listener: function(msg, consumerArg) {
console.log(new Date().toLocaleString(), msg.getData().toString());
consumerArg.acknowledge(msg);
}
});
/*
* Those lines are commented, because they re-produce the issue.
* Since they are commented, there is no active reference for the consumer being created
*/
//await consumer.close(); …
```
> Consumer with message listener dies after some time

- src/Consumer.cc
- src/Consumer.h
- tests/consumer.test.js
Fixes issue raised here: https://github.com/apache/pulsar-client-node/issues/62#issuecomment-612976617
We do `Unref` more than once in the old code, now we do `Unref` only if the consumer is closed.
> Fix consumer double close

- examples/consumer_listener.js
In this PR, add simple listener consumer example to `examples/`.
> Add listener consumer example

- src/Consumer.cc
- src/Consumer.h
When the following code is executed, the node process is not finished in spite of consuming all messages and closing the consumer and client.
```
const Pulsar = require('pulsar-client');
(async () => {
serviceUrl: 'pulsar://localhost:6650',
});
let received = 0;
let finish;
const finishPromise = new Promise((resolve) => {
finish = resolve;
});
const consumer = await client.subscribe({
subscription: 'sub1',
listener: (msg, msgConsumer) => {
const data = msg.getData().toString();
console.log(data);
msgConsumer.acknowledge(msg);
received += 1;
if (received === 10) finish();
},
});
await finishPromise;
await consumer.close();
await client.close();
})();
```
It seems that this happens because the registered …
> Fix Cleanup Listener

- README.md
The Node.js library version 1.2.0 requires the C++ library 2.5.0 or later.
> Updated compatibility table in README.md

- src/Message.cc
- tests/conf/standalone.conf
- tests/end_to_end.test.js
Updates ```Message.cc``` to include support for delayed delivery from the C++ client. (```pulsar_message_set_deliver_after``` & ```pulsar_message_set_deliver_at```)
> Adds deliverAt and deliverAfter support to Producer

- src/Producer.cc
- src/Producer.h
- tests/producer.test.js
It simply hooks up `pulsar_producer_get_topic` and `pulsar_producer_get_producer_name` so the JS client can have access to these values.
> Adds getProducerName and getTopic to Producer

- src/Consumer.cc
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- tests/consumer.test.js
- tests/end_to_end.test.js
Implements a quick-and-dirty hack to get RegEx support working for topics in consumers by spinning using ```std::this_thread::yield()``` in ```Napi::AsyncWorker```'s ```Execute``` function while waiting for callbacks. This allows the ```pulsar_client_subscribe_pattern_async``` and ```pulsar_client_subscribe_async``` functions to be used from the C++ library.
> Adds Pattern/RegEx Support to Consumer

- src/Consumer.cc
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- tests/consumer.test.js
- tests/end_to_end.test.js
Adds multi-topic support from the C++ library by utilizing ```pulsar_client_subscribe_multi_topics_async```. This accommodates the issue here: https://github.com/apache/pulsar-client-node/issues/12
> Add Multi-Topic Support to Consumer

- package-lock.json
When running `npm install`, I got the following warning, so ran `npm audit fix`.
```
found 2 low severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
```
> Upgrade package that has security vulnerabilities

- .github/workflows/nodejs.yml
- index.d.ts
- package-lock.json
- package.json
- tstest.ts
Some files did not have license headers, so added them. In addition, I rolled back `license-check-and-add` to the previous version because `npm run license:addheader` didn't working properly.
> Add license headers to some files

- index.d.ts
- tstest.ts
The constructor of the `AuthenticationAthenz` class can accept one string or object as an argument, but currently there is only a type definition for string. So I added a type definition to accept the object type argument.
> Add definition of AthenzConfig

- src/Message.cc
Support disable replication.
Because `disableReplication` is not working in pulsar-client-cpp 2.7.0 or previous version, needs 2.7.1 or later version. 
This bug was fixed in https://github.com/apache/pulsar/pull/9372
> Support Disable Replication

- .eslintrc.json
- package-lock.json
- package.json
- tests/consumer.test.js
- tests/producer.test.js
- tests/reader.test.js
This PR is to avoid segmentation fault on ci tests.
I don't know root cause, but it seems that we can avoid segmentation fault by adding client.close after test is finished.
> Call client.close on tests

- examples/reader_listener.js
- src/Reader.cc
- src/Reader.h
- src/ReaderConfig.cc
- src/ReaderListener.h
- tests/end_to_end.test.js
Add listener function to the Reader, using the C++ client listener support.
- Add listener for reader
- Add example and e2e test of using the reader listener
> Support Reader Listener

- src/MessageId.cc
I run the following code with valgrind and it looks like there are a memory leak in MessageId::ToString.
```
// Receive messages
for (let i = 0; i < 1000; i += 1) {
const msg = await consumer.receive();
console.log(msg.getMessageId().toString());
console.log(msg.getData().toString());
consumer.acknowledge(msg);
}
```
```
...
==20476== 13,890 bytes in 1,000 blocks are definitely lost in loss record 68 of 68
==20476==    at 0x4C29F73: malloc (vg_replace_malloc.c:309)
==20476==    by 0x5B03BD9: strndup (in /usr/lib64/libc-2.17.so)
==20476==    by 0x9EA3D74: pulsar_message_id_str (in /usr/lib/libpulsar.so.2.7.1)
==20476==    by 0x9A73E6A: MessageId::ToString(Napi::CallbackInfo const&) (in /home/k2la/pulsar-client-node/build/Release/Pulsar.node)
==20476==    by 0x9A7BFE0: …
```
> Fix Leak in MessageId::ToString

- src/MessageId.cc
`MessageId::Serialize` possibly have a memory leak bug. Here are a simple reproduce code and valgrind log.
```js
for (let i = 0; i < 1000; i += 1) {
const msg = await consumer.receive();
// serialize
const serialize = msg.getMessageId().serialize();
console.log(serialize);
consumer.acknowledge(msg);
}
```
```
==1048== 7,000 bytes in 1,000 blocks are definitely lost in loss record 67 of 68
==1048==    at 0x50F4F73: malloc (vg_replace_malloc.c:309)
==1048==    by 0xA36C67A: pulsar_message_id_serialize (in /usr/lib/libpulsar.so.2.7.2)
==1048==    by 0x9F3E599: MessageId::Serialize(Napi::CallbackInfo const&) (in /app/node_modules/pulsar-client/build/Release/Pulsar.node)
==1048==    by 0x9F458D0: Napi::InstanceWrap<MessageId>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) …
```
> Fix leak at MessageId::Serialize

- src/Message.cc
In our enviroment, sometimes we get following error.
```
#
#
#
#
#FailureMessage Object: 0x7ffe7bd5eda0
1: 0xa92851  [node]
2: 0x1a1ac64 V8_Fatal(char const*, ...) [node]
3: 0xe7e119 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
4: 0xbc7e48 v8::ArrayBuffer::GetBackingStore() [node]
5: 0x9e3a80 napi_get_typedarray_info [node]
6: 0x7f815dd9f669 Message::GetData(Napi::CallbackInfo const&) [/root/pulsar-client-node/build/Release/Pulsar.node]
7: 0x7f815dda3aa1 Napi::ObjectWrap<Message>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*) [/root/pulsar-client-node/build/Release/Pulsar.node]
8: 0x9da63f  [node]
9: 0xc06acb  [node]
10: 0xc08076  [node]
11: 0xc086f6 v8::internal::Builtin_HandleApiCall(int, unsigned long*, …
```
> Use Buffer::Copy instead of Buffer::New

- binding.gyp
When compiling pulsar-client-node with gcc4.9 and node v16.5.0, build failed with following error.
```
g++: error: unrecognized command line option ‘-std=gnu++14’
make: *** [Release/obj.target/Pulsar/src/addon.o] Error 1
make: Leaving directory `/root/pulsar-client-node/build'
```
Gcc4.9 does not support `-std=gnu++14` option, but this option was added to common.gypi intead of `-std=gnu++1y` from node v16.2.0.
https://github.com/nodejs/node/blob/v16.2.0/common.gypi#L378
Also added `-std=gnu++17` option from node v17.1.0.
https://github.com/nodejs/node/blob/v17.1.0/common.gypi#L388
Add `-std=gnu++11` option to `cflags_cc` and remove `-std=gnu++14/17` options from it because pulsar-client-node can be compiled with just `-std=gnu++11` option.
> Fix cflags_cc for gcc-4.9

- .gitignore
Recently, the release process for the Node.js client has been modified and added a step to create a tarball of this repository.
```sh
$ git archive HEAD --prefix=pulsar-client-node-1.X.0/ --output pulsar-client-node-1.X.0.tar.gz
```
I added two file extensions to `.gitignore` to prevent this tarball from being committed.
> Add tarball files to .gitignore

- package-lock.json
I ran `npm audit fix` to fix security vulnerabilities.
```
$  npm audit
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ node-fetch is vulnerable to Exposure of Sensitive            │
│               │ Information to an Unauthorized Actor                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @mapbox/node-pre-gyp                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @mapbox/node-pre-gyp > …
```
> Upgrade libraries with security vulnerabilities

- package.json
There is a step in [the release process](https://github.com/apache/pulsar-client-node/wiki/Release-process) to run `npm run license: addheader`, which will add the license header to the source file archive (pulsar-client-node-1.X.0.tar.gz) and corrupt the file.
To avoid this, I modified the setting so that the license header is not added to files with the file extension `.gz`.
> Do not add license header to tarball file

- package-lock.json
`minimist` module has a security vulnerability, so I ran `npm audit fix` to upgrade it. 
```sh
$ npm audit
minimist  <=1.2.5
Severity: high
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
> Upgrade minimist to 1.2.6

- README.md
- package.json
Currently, users can't find https://pulsar.apache.org/docs/en/client-libraries-node on [github](https://github.com/apache/pulsar-client-node) and [npmjs](https://www.npmjs.com/package/pulsar-client).
> Add a pulsar nodejs client document link to package.json/README

- README.md
- binding.gyp
On macOS and Apple Silicon, we can't build pulsar-client-node if using default environment variables like below.
https://github.com/apache/pulsar-client-node/issues/87#issuecomment-1157411697
```
% echo $LIBRARY_PATH
% PULSAR_CPP_DIR=/opt/homebrew/Cellar/libpulsar/2.10.0 npm install
...
ld: library not found for -lpulsar
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Debug/Pulsar.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! …
```
> Split conditions between OS in binding.gyp

- src/Consumer.cc
There is a segmentation fault reported by a user.
> So, I recompiled the extension with `node-gyp rebuild --debug` then attached a debugger and it crashed because of this
>
> ```
> (gdb) l
> 60      void MessageListenerProxy(Napi::Env env, Napi::Function jsCallback, MessageListenerProxyData *data) {
> 61        Napi::Object msg = Message::NewInstance({}, data->cMessage);
> 62        Consumer *consumer = data->consumer;
> 63        delete data;
> 64
> 65        jsCallback.Call({msg, consumer->Value()});
> 66      }
> 67
> 68      void MessageListener(pulsar_consumer_t *cConsumer, pulsar_message_t *cMessage, void *ctx) {
> 69        ListenerCallback *listenerCallback = (ListenerCallback *)ctx;
> (gdb)
> ```
>
> On line 65, consumer is actually null 
The `consumer` field is assigned from …
> Add null check for consumer in MessageListenerProxy

- package-lock.json
- package.json
From https://github.com/apache/pulsar-client-node/pull/38 , node-pre-gyp was installed as a dependency.
Also, it tries to download a pre-built binary when we install pulsar-client.
However, pre-built binaries are not uploaded yet.
```
npm ERR! node-pre-gyp http GET https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.6.2-node-v83-linux-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.6.2-node-v83-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for pulsar-client@1.6.2 and node@14.17.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on …
```
> Remove node-pre-gyp dependency and config

- src/ProducerConfig.cc
Fixes #230 
This change should help avoid `ProducerQueueIsFull` errors when producing to a partitioned topic with batchingEnabled.
> Respect maxPendingMessagesAcrossPartitions

- src/ProducerConfig.cc
Fix the following lint error.
```
$ npm run lint
> pulsar-client@1.7.0-rc.0 lint
> clang-format-lint src/*.cc src/*.h && eslint --ext .js .
Error: Formatting incorrect on "src/ProducerConfig.cc", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='5055' length='0'>&#10;          </replacement>
<replacement offset='5083' length='62'> </replacement>
</replacements>
```
> Format ProducerConfig.cc

- docs/release-process.md
#235 and #238 support downloading prebuilt binary when `npm install`. This requires us to upload binaries to Apache dist when we release.
- Move the release process doc to the repo. Subsequent changes are made via PR, which can allow non-commiters to change and keep a record of the changes.
- You can view the changes through this [commit](https://github.com/apache/pulsar-client-node/pull/243/commits/62b3d3ae6fc2374a92ec99cf650756d4cbc47643).
> [refactor] Change release process

- README.md
- pkg/mac/common.sh
#235 and #238 support downloading prebuilt binary when `npm install`. This simplifies installation for users. 
- Modify the README to apply the new install and build method.
> [refactor] Modify the README to apply the new installation method

- pkg/windows/download-cpp-client.bat
https://github.com/apache/pulsar-client-node/issues/256
- Get local `arch` when the `arch` is empty.
- Use `move` instead of `mv`
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
> Fix windows default download cpp client failed.

- README.md
- examples/consumer.js
- examples/consumer_listener.js
- examples/consumer_tls_auth.js
- examples/encryption-consumer.js
- examples/encryption-producer.js
- examples/producer.js
- examples/producer_tls_auth.js
- examples/reader.js
- examples/reader_listener.js
Currently, the scripts in `examples` directory all requires a
`pulsar-client` module installed. However, they might use some latest
APIs that were not included in official releases. We should force users
to build the client before running the examples.
Change `require('pulsar-client')` to `require('..')` in all `*.js`
scripts under the `examples` directory.
Simplify the README to two parts:
1. How to install the official released `pulsar-client` module. Then add a very simple end-to-end example.
2. How to build the artifacts and run the examples based on latest code.
> Change the require path in examples and refactor README

- .github/workflows/ci-build-release-napi.yml
- .github/workflows/ci-pr-validation.yml
- dependencies.yaml
- pkg/mac/build-cpp-deps-lib.sh
- pkg/mac/build-cpp-lib.sh
#235 and #238 support prebuild binaries. However, the MacOS arm64 arch is not yet supported.
- Supoort prebuild macos-arm64 arch binaries.
- Fixed the x64 architecture prebuild name error. #249  
You can download it [here](https://github.com/shibd/pulsar-client-node/suites/9522179570/artifacts/452316640) to validate the ARM64 prebuild binaries.
> Supoort prebuild macos-arm64 arch binaries.

- examples/custom_logger.js
- index.js
Currently, there is no example or documentation to show how to use the custom logger.
* Add an example to show how to use the custom logger
* Add `toString` method to `Pulsar.LogLevel` to convert logLevel number to string
Run `node examples/custom_logger.js`
Output:
```
[INFO][ClientConnection:189] [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
[INFO][ConnectionPool:97] Created connection for pulsar://localhost:6650
[INFO][ClientConnection:379] [127.0.0.1:50422 -> 127.0.0.1:6650] Connected to broker
[INFO][HandlerBase:72] [persistent://public/default/my-topic, ] Getting connection from pool
[INFO][ProducerImpl:190] [persistent://public/default/my-topic, ] Created producer on broker [127.0.0.1:50422 -> 127.0.0.1:6650] 
[INFO][Client:87] Subscribing on Topic …
```
> Add example for custom logger and LogLevel.toString

- .github/workflows/ci-pr-validation.yml
- package-lock.json
- package.json
In #235, wrong introduction of `verbose` dependencies. It will cause the installation to fail using `yarn install`.
- Remove `verbose` dependence.
- Remove `node-pre-gyp-github`, is also useless dependence. It is responsible for publishing NAPI to Release page. Refer #245; We don't need to publish.
- Compile NAPI of macOS with yarn to verify that `yarn` is available.
- Update package.lock.json file.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration …
> Remove useless dependencies.

- pkg/linux/Dockerfile_linux_glibc
- pkg/linux/download-cpp-client.sh
The latest version of pulsar-client does not work on Rocky Linux 8.
```sh
$ head -n 2 /etc/os-release
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
$ npm ls
nodejs@ /home/massakam/temp/nodejs
└── pulsar-client@1.8.0
$ node consumer.js
node:internal/modules/cjs/loader:1243
return process.dlopen(module, path.toNamespacedPath(filename));
^
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/massakam/temp/nodejs/node_modules/pulsar-client/lib/binding/Pulsar.node)
at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
at Module.load (node:internal/modules/cjs/loader:1037:32)
at Module._load (node:internal/modules/cjs/loader:878:12)
at Module.require (node:internal/modules/cjs/loader:1061:19)
at require …
```
> Fix an issue where the latest client does not work on Rocky Linux 8

- docs/release-process.md
The versioning rule of Node.js Client is not explicitly written.
Add Versioning Rule to Release process.
> Add Versioning Rule to Release Process

- index.d.ts
- tstest.ts
Add schema typing to consumer and producer
> [improve][client] Add schema typing to consumer and producer

- binding.gyp
- package.json
Currently, we can't use `the npm config argument: --{module_name}_binary_host_mirror` if we want to download binary files through a mirror.
https://github.com/mapbox/node-pre-gyp/blob/v1.0.9/README.md#download-binary-files-from-a-mirror
This is because npm will use npm_config_**p**ulsar_binary_host_mirror for the environment variable name even if running `npm install pulsar-client --Pulsar_binary_host_mirror=<mirror url>`.
Therefore, we cant' set mirror url correctly.
* Rename binary module_name from Pulsar to pulsar
> Rename binary module_name from Pulsar to pulsar

- pulsar-client-cpp.txt
There is a regression bug in Pulsar C++ client 3.1.0.
https://lists.apache.org/thread/81dwlq1vb21pq1jt83okqln8oyc3c2wj
- Upgrade CPP client version to 3.1.1
> Upgrade cpp client version to 3.1.1

- package-lock.json
ansi-regex-2.1.1 is now required by node-pre-gyp dependency, but that version has security vulnerabilities.
https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908
```
@mapbox/node-pre-gyp@1.0.9 > npmlog@5.0.1 > gauge@3.0.2 > 
wide-align@1.1.3 > string-width@1.0.2 > strip-ansi@3.0.1 > ansi-regex@2.1.1
```
Upgrade ansi-regex by running `npm update wide-align string-width`.
```
@mapbox/node-pre-gyp@1.0.9 > npmlog@5.0.1 > gauge@3.0.2 > 
wide-align@1.1.5 > string-width@4.2.3 > strip-ansi@6.0.1 > ansi-regex@5.0.1 
```
ansi-regex-2.1.1 is required only in devDependencies after merging this pr.
> Upgrade ansi-regex

- pulsar-client-cpp.txt
`CPP_CLIENT_BASE_URL` ends with `/`, which seems unnecessary.
```sh
$ find . -type f | xargs grep --color 'CPP_CLIENT_BASE_URL'
./pkg/linux/download-cpp-client.sh:  curl -L -O ${CPP_CLIENT_BASE_URL}/deb-${PLATFORM}/apache-pulsar-client-dev.deb
./pkg/linux/download-cpp-client.sh:  curl -L -O ${CPP_CLIENT_BASE_URL}/apk-${PLATFORM}/${UNAME_ARCH}/apache-pulsar-client-dev-${CPP_CLIENT_VERSION}-r0.apk
./pkg/linux/download-cpp-client.sh:  curl -L -O ${CPP_CLIENT_BASE_URL}/rpm-${PLATFORM}/${UNAME_ARCH}/apache-pulsar-client-devel-${CPP_CLIENT_VERSION}-1.${UNAME_ARCH}.rpm
./pkg/mac/build-cpp-lib.sh:curl -O -L "$CPP_CLIENT_BASE_URL"/apache-pulsar-client-cpp-${CPP_CLIENT_VERSION}.tar.gz
./pkg/windows/download-cpp-client.bat:curl -O -L %CPP_CLIENT_BASE_URL%/%arch%-windows-static.tar.gz …
```
> Remove unnecessary / at the end of CPP_CLIENT_BASE_URL

- package.json
The binary.host URL is not stable. It will be invalid in the future. See: 
https://github.com/apache/pulsar-client-node/blob/master/docs/release-process.md?plain=1#L242-L246
* Use `archive.apache.org`. This URL is stable and will not be invalid.
> [fix] Fix the binary host url

- .github/workflows/ci-pr-validation.yml
- pkg/linux/Dockerfile_linux_glibc
- pkg/linux/download-cpp-client.sh
- pkg/load_test.js
- tests/docker-load-test.sh
- tests/load-test.sh
Fixes https://github.com/apache/pulsar-client-node/issues/286
The maximum GLIBCXX version on CentOS 7 is 3.4.19. If we want to use the Pulsar Node client on CentOS 7, we have to upgrade the libstdc++.so. The reason is the libstdc++ version is too high for some systems. https://github.com/apache/pulsar-client-node/pull/285 downgrades the base image to `node:18-buster` but it still requires the `GLIBCXX_3.4.22`.
- Use `centos:7` as the base image to build `Pulsar.node` for glibc-based Linux distributions.
- Add `load_test.sh` to verify `Pulsar.node` can be loaded by other docker images and test Node.js 16 and 19 on Debian buster and bullseye.
> Make it compatible with GLIBCXX_3.4.19 (CentOS 7)

- pulsar-client-cpp.txt
There is a TLS-related bug in Pulsar C++ client 3.1.1.
- Upgrade the depend on cpp version to 3.1.2.
> Upgrade the depend on cpp version to 3.1.2.

- docs/release-process.md
Optimize release process.
- When publishing `rc` version to the npm registry, add `rc` tag to distinguish the release candidate from the official release.
> [doc] Optimize release process.

- .gitignore
- GenCertFile.js
- index.js
- package.json
- src/Client.js
Master Issue: #281 
After 1.8.0, we helped users precompile CPP, resulting in users not being able to obtain system certificates when using TLS-related functions.
Current usage issues list reference: https://github.com/BewareMyPower/pulsar-tls-examples
Node.js provides [bundled Mozilla CA](https://nodejs.org/api/tls.html#tlsrootcertificates), which we can use by default.
- Use Node.js bundled Mozilla CA when `tlsTrustCertsFilePath` is empty.
- Since the CPP client can't set cert content direct, we first need to write the certificate content to a file and pass in the path to the CPP client.
You can clone the [repository](https://github.com/shibd/pulsar-client-tls-test) installation and verify:
```
git clone git@github.com:shibd/pulsar-client-tls-test.git
npm install
node tls-oauth2.js
node …
```
> Use the certificate provided by the node.js

- .github/workflows/ci-pr-validation.yml
- binding.gyp
If fetching pre-built binaries from a remote server fails, node-pre-gyp will try to fallback to building locally. However, even if the Pulsar C++ library is installed locally, this build does not succeed. This is because the C++ library must have been downloaded by a script under the `pkg` directory in this repository. Normal users other than Pulsar developers do not do this.
```sh
$ npm i pulsar-client-1.9.0-rc.0.tgz
...
npm ERR! g++: error: ../pkg/linux/pulsar-cpp/lib/libpulsarwithdeps.a: No such file or directory
```
Fixed `binding.gyp` to try to link to shared libraries installed by package managers such as Homebrew, RPM and APT if no C++ libraries are downloaded under the `pkg` directory.
> [fix] Fix error when falling back to local build

- .github/workflows/ci-pr-validation.yml
- pkg/linux/Dockerfile_linux_musl
- tests/load-test.sh
Fixes #299 
The root cause is that pulsar-client is not compatible with `alpine3.15`. 
Currently, the binary file is compiled with the default version of alpine(3.16).
https://github.com/apache/pulsar-client-node/blob/768e76f6dc0e03f9b5aa330ffde449f67ade52a2/pkg/linux/Dockerfile_linux_musl#L22
- Specifies that compilation is used with `alpine3.15` version.
- Test NAPI file in alpine3.15 env.
> [fix] not compatible with alpine 3.15 env

- src/Client.cc
- tests/client.test.js
Fixes #303 
The `std::invalid_argument` exception causes the node process to exit directly, we should wrap it as a node exception that the user can catch.
- Wrap c++ exception when creating client.
> [Fix] Wrap c++ exception when creating client.

- .gitignore
- README.md
> chore: update gitignore and add note in README

- binding.gyp
Fixes #283 
The root cause is the OpenSSL symbol conflict between Node.js and CPP client.
In versions after Node.js 17 or greater, the OpenSSL version was upgraded to 3.0.0, and the cpp client used v1.1.1 of Openssl. 
Therefore, it results in a segmentation fault when users use TLS-related features.
- When building `pulsar.node`, use `"-Wl,--exclude-libs,ALL"` config to hidden symbol.
You can use this [repo](https://github.com/shibd/pulsar-client-tls-test.git) to verify it.
I have verified that the environment has:
Image:
- node:16
- node:16-alpine
- node:17
- node:17-alpine
- node:18
- node:18-alpine
- node:19
- node:19-alpine
BTW: I will add tls-relate unit test in subsequent PR. …
> Fix symbols conflict of OpenSSL.

- .gitignore
- README.md
- package-lock.json
- package.json
- tests/run-unit-tests.sh
- tslint.json
- tstest.ts
- typedoc.json
This closes https://github.com/apache/pulsar/issues/19876.
Perhaps I'll pick this change to branch-1.8 and generate the first API docs for hosting on our website.
> docs: add typedoc to generate apidoc 

- perf/perf_producer.js
I noticed the `perf_producer` is not working properly as follows. I want to fix it.
```
% node perf/perf_producer.js -u pulsar://localhost:6650 -t persistent://public/default/my-topic -i 1000
----------------------
size: 1024
url: pulsar://localhost:6650
topic: persistent://public/default/my-topic
iteration: 1000
messages: 1000
----------------------
/Users/equanz/src/pulsar-client-node/perf/perf_producer.js:107
histogram.getMean(),
^
TypeError: histogram.getMean is not a function
at /Users/equanz/src/pulsar-client-node/perf/perf_producer.js:107:17
Node.js v18.6.0
```
* Modify the `perf_producer` to address [migration procedures](https://github.com/HdrHistogram/HdrHistogramJS/tree/v2.0.1#migrating-from-v1-to-v2)
This change is a trivial …
> [fix][perf] Modify perf_producer to run properly

- src/Client.h
- src/Consumer.cc
- src/Consumer.h
- src/LogUtils.h
- tests/end_to_end.test.js
Currently, there is no error handling for the message listener. If any errors are thrown from the user's listener, the program will crash.
* Add error handling for the message listener. The client won't crash the program if there are any errors in the user function. Instead, it will log as the error.
* Add LogUtils to the internal native code.
* Add `GetTopic` and `GetSubscriptionName` for the internal native consumer.
Currently, there is no error handling for the message listener. The program will crash if any errors are thrown from the user's listener.
* Add error handling for the message listener. The client won't crash the program if there are any errors in the user function. Instead, it will log as the error.
* Add LogUtils to the internal native code.
* Add `GetTopic` and …
> [Improve] Add error handling for the message listener

- README.md
The new [client feature matrix](https://pulsar.apache.org/client-feature-matrix/) page has been live, so this PR makes the required updates on the doc side.
Add a paragraph to notify both users and contributors about the new client feature matrix.
> [Doc] Add links to client feature matrix in README.md

- index.d.ts
- src/Client.cc
- src/Client.h
- src/Client.js
- tests/client.test.js
Master Issue: #320 
Support api: [client.getPartitionsForTopic](https://pulsar.apache.org/api/cpp/3.1.x/classpulsar_1_1_client.html#a208629aff52395ad0072622ae82f5657)
Just bind CPP function: `pulsar_client_get_topic_partitions_async` to JS.
> [feat]: Support client.getPartitionsForTopic (#320)

- build-support/pulsar-test-service-start.sh
- tests/consumer.test.js
- tests/producer.test.js
Using the latest pulsar version to run unit tests helps us develop new features and test compatibility on time.
- Upgrade unit test depends on the pulsar version to the latest(currently 3.0.0).
- All unit test pass means ok.
> Upgrade unit test depends on the pulsar version to the latest(currently 3.0.0)

- src/Reader.cc
Currently if there is something wrong with `pulsar_reader_has_message_available`, the log will not print the actual error message. It's hard to debug without that message.
* Add failed result message to the log in Reader::HasNext.
> [Improve] Improve log message for Reader.HasNext

- examples/encryption-reader.js
- index.d.ts
- src/ReaderConfig.cc
- tests/end_to_end.test.js
- tstest.ts
Fixes #276 
With the underlying C library exposing the required reader config options for enabling encryption, the Node.js library can now also support end-to-end encryption when reading from a topic. 
- Added handling of config options required for encryption to work to the NAPI part
- Added those options to the type definition
- Added an example how to configure a Reader that reads from an encrypted topic
- Added tests
- added integration test
I'm unsure what to check here since I've added an example how to create a Reader that's using encryption. But the compatibility matrix needs to be …
> [feat] End-to-end encryption support for Reader

- tests/client.test.js
- tests/http_utils.js
- tests/reader.test.js
Master Issue: #321 
CPP Client 3.2.0 support a partitioned reader. This PR add a partitioned topic unit test for Reader.
- Create a http_utils.js to abstract creation partitioned topic.
- Add a partitioned topic unit test for Reader.
- Reader by Partitioned Topic will cover it.
> Add partitioned topic unit test for Reader.

- .github/workflows/ci-pr-validation.yml
Currently, ci has always failed. The root cause is brew auto upgrade dependents lib version.
https://github.com/apache/pulsar-client-node/actions/runs/5242136286/jobs/9469835451?pr=331
- Use HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK to disable this behaviour.
> Fix CI always failed.

- index.d.ts
- src/ProducerConfig.cc
- tests/producer.test.js
#269 
- Expose the producer access mode option.
- Improve producer.test related unit test.
Need to add examples docs on here: https://pulsar.apache.org/docs/3.0.x/client-libraries-producers/#configure-access-mode
> feat: support producer access mode.

- index.d.ts
- src/ConsumerConfig.cc
- tests/consumer.test.js
Master Issue: #<xyz>
Support pattern subscription non-persistent topic.
- Expose `RegexSubscriptionMode ` config to set pattern subscription mode.
- Add Regex subscription unit test to cover when RegexSubscriptionMode = AllTopic case. More case cover by cpp clients.
https://pulsar.apache.org/docs/next/client-libraries-consumers/ 
Here not about pattern subscription anyone's docs or examples yet, need to add them in the future.
> feat: support pattern subscription non persistent topic.

- GenCertFile.js
- index.js
- package-lock.json
- package.json
- pkg/load_test.js
- tests/client.test.js
- tests/consumer.test.js
- tests/end_to_end.test.js
- tests/producer.test.js
- tests/reader.test.js
There seems to be a security vulnerability in the `semver` module that `@mapbox/node-pre-gyp` depends on, so I will upgrade these.
https://nvd.nist.gov/vuln/detail/CVE-2022-25883
- Upgrade `@mapbox/node-pre-gyp` to 1.0.11
- Upgraded `semver` to versions with vulnerability fixes
> Upgrade semver

- .github/workflows/ci-pr-validation.yml
- license-checker-config.json
- package-lock.json
- package.json
The [license-check-and-add](https://www.npmjs.com/package/license-check-and-add) module used in this repository was a very old version, so I upgraded it to the latest version. Additionally, I added a license header check to the CI job.
> Upgrade license-check-and-add to 4.0.5

- examples/consumer_listener.js
This PR fixes an potential issue of examples/consumer_listener.js where client connections could be unintentionally disconnected.
In the code below, which is a modified version of examples/consumer_listener.js, the connection is disconnected after a few seconds. I want to fix it.
```
const Pulsar = require('../');
(async () => {
// Create a client
serviceUrl: 'pulsar://localhost:6650',
});
Pulsar.Client.setLogHandler((level, file, line, message) => {
console.log('[%s][%s:%d] %s', level, file, line, message);
});
// Create a consumer with listener
const consumer = await client.subscribe({
subscription: 'sub1',
subscriptionType: 'Shared',
listener: (msg, msgConsumer) => {
console.log(msg.getData().toString()); …
```
> [fix] Fixed an potential issue of examples/consumer_listener.js where clients were unintentionally disconnected

- .github/workflows/ci-build-release-napi.yml
- .github/workflows/ci-pr-validation.yml
Currently, following jobs are failed.
```
Build NAPI macos - Node 18 - arm64
Build NAPI macos - Node 18 - x64
Build NAPI macos with CPP lib installed by Homebrew 
```
log
```
gyp info using node-gyp@9.4.0
gyp info using node@18.18.2 | darwin | x64
gyp info find Python using Python version 3.12.0 found at "/usr/local/bin/python3"
.
.
.
File "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
import gyp  # noqa: E402
^^^^^^^^^^
File "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
import gyp.input
File "/Users/runner/hostedtoolcache/node/18.18.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, …
```
> [ci] use python-3.10

- index.d.ts
- tstest.ts
Athenz support x.509 certificate and `tokenExpirationTime`  param has been removed at  https://github.com/apache/pulsar-client-cpp/pull/274 .
* Add type definition for athen x.509 certificate
* Mark tokenExpirationTime as deprecated
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
(Docs have been …
> Add type definition for AthenzX509Config

- index.d.ts
- src/Consumer.cc
- src/Consumer.h
- src/ConsumerConfig.cc
- src/ConsumerConfig.h
- src/ThreadSafeDeferred.cc
- src/ThreadSafeDeferred.h
- tests/consumer.test.js
Master Issue: #274
#274  Support batch receive for the consumer.
- Add batch receive policy config on the consumer.
- Add batch receive interface on the consumer.
- Refactor consumer `config set` and `verify logic`. 
- Since config set logic with verify logic for the consumer is separate, it will be more complicated to read the code and subsequent extensions. 
- Add batch receive unit test on Consumer.
- Add more config verify unit test on Consumer.
> feat: Support batch receive for consumer.

- docs/release-process.md
Add api docs section for release process.
Add api docs section for release process.
> Add api docs section for release process.

- index.d.ts
- src/Client.cc
- tests/conf/standalone.conf
- tests/end_to_end.test.js
Fixes #214 
This library doesn't provide a way to pass a custom listener name to a Pulsar client, which is necessary if you have multiple advertised listeners and want to hit the non-default one: https://pulsar.apache.org/docs/next/concepts-multiple-advertised-listeners/
After https://github.com/apache/pulsar-client-cpp/pull/370, `getListener` and `setListener` are now exposed in the C API, and can be used by this library as well.
- added `listenerName` to e2e tests where necessary (uses first `advertisedListener` by default)
> [feat] Add listenerName to client config

- src/Reader.cc
- tests/reader.test.js
#374 
- Add a null check for the reader in ReaderListenerProxy
- Add reader test to cover it.
> fix: ReaderListenerProxy will make a segfault

- README.md
- package.json
- src/Client.js
- https://github.com/apache/pulsar-client-node/issues/226#issuecomment-1917492231
- https://lists.apache.org/thread/6rmk2m09q1c4f2g3s8thf5fgd0vsfryv
After #301, will use the [Mozilla CA](https://nodejs.org/api/tls.html#tlsrootcertificates) certificate provided by the node.js. And use the `fs.rmSync` API to generate a local ca when install.
But the [fs.rmSync](https://nodejs.org/api/fs.html#fsrmsyncpath-options) was introduced in Node.js v14.14.0, so an error will occur when installing now.
```
TypeError: fs.rmSync is not a function
```
- Use `fs.existsSync and unlinkSync ` instead of `fs.rmSync`.
- Since [Mozilla CA](https://nodejs.org/api/tls.html#tlsrootcertificates) requires a Node.js version greater than `v12.3.0`, the `README` and `package.json` should be modified to indicate that it …
> fix: Compatible with Node 12.3.0 and higher versions.

- .github/workflows/ci-build-release-napi.yml
- .github/workflows/ci-pr-validation.yml
For now, GitHub support MacOS arm64 runnner.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
- x86_64 -> macos-13
- arm64 -> macos-14
We can use the corresponding runner to compile the tests instead of cross-compiling. 
- Separate the compilation model of different macOS architectures.
- All ci need passed.
> feat: Use macos-arm64 github runnner to build napi package

- pkg/linux/Dockerfile_linux_glibc
Compile glibc binaries using node:buster instead of centos7 for two reasons:
1. Binaries compiled with centos7 may not be compatible with the node:buster (glibc) environment.
2. Centos7 has reached its [End of Life (EOL)](https://www.redhat.com/en/topics/linux/centos-linux-eol#:~:text=CentOS%20Linux%207%20will%20reach%20end%20of%20life%20(EOL)%20on,can%20help%20ease%20your%20migration)."
Use `node:${NODE_VERSION}-buster` to build glibc-type binaries.
1. Multi linux_glibc oss verify passed.
https://github.com/apache/pulsar-client-node/blob/13c285989743aa37e5c2b2909fadef0d343b228e/.github/workflows/ci-pr-validation.yml#L173-L179
2. Self-release build passed and verified passed.
https://github.com/shibd/pulsar-client-node/releases/tag/v1.11.0-fix.1
You can install it by: `npm install …
> fix: Compile glibc binaries using node:buster instead of centos7

- index.d.ts
- index.js
- src/Authentication.cc
- src/AuthenticationBasic.js
- tstest.ts
Add HTTP basic for node client
Adaptation of "Feature support oauth2 for node client (#190)" for HTTP basic Authn
> [feat] Support HTTP basic for node client

- pulsar-client-cpp.txt
Bump cpp client version to v3.6.0
Bump cpp client version to v3.6.0
> Bump cpp client version to v3.6.0

- examples/custom_logger.js
- index.d.ts
- src/Client.cc
- src/Client.h
Currently, when setting the log handler it uses the info level by default. 
https://github.com/apache/pulsar-client-cpp/blob/2a6916819b2a80a532f827dc96026b8fdc0b15ed/lib/c/c_ClientConfiguration.cc#L107-L109
- Support set log level of cpp client
- You can run examples/custom_logger.js to verify it.
> Support set log level of cpp client

- .github/workflows/ci-build-release-napi.yml
- build-support/download-release-artifacts.py
- build-support/stage-release.sh
1. Change upload-artifact to v4: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
2. Rewrite the download script: because original will get error, details rerfer to: https://github.com/orgs/community/discussions/88698
- verify it when released 1.13
> Fix release workflow and script

- src/Authentication.cc
#395 Introduce a regression on `node:20-alpine` env. if use a token to connect to pulsar, will get a segmentation fault when client closes.
```
[INFO][ClientConnection:282] [10.88.0.2:51556 -> 34.28.200.175:6651] Destroyed connection to ****
[INFO][ClientConnection:282] [10.88.0.2:51544 -> 34.28.200.175:6651] Destroyed connection to ****
Bus error (core dumped)
```
Happend here:
https://github.com/apache/pulsar-client-node/blob/c52bd1b89ca4fb76117f29215f6b0cbeb8ee8f1d/src/Authentication.cc#L181-L183
- We need to explicitly set `tokenSupplier` to `nullptr`, as uninitialized pointers in C++ have undefined default values.
- Verified on my local test.
> Fix segmentation fault when use token auth

- pkg/linux/download-cpp-client.sh
* Variables in the script should be enclosed in double quotes.
```
./download-cpp-client.sh: line 26: [: !=: unary operator expected
```
* Enclose variables in double quotes in download-cpp-client.sh
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
> Fix: Enclose variables in double quotes

- index.d.ts
- src/Client.cc
- tests/end_to_end.test.js
In the C++ client, the `connectionTimeout` parameter controls the time allowed to establish a connection, with a default value of 10 seconds
https://github.com/apache/pulsar-client-cpp/blob/4ba83e83fbb4319c0b4cda82372caf042e9ccaa6/lib/ClientConnection.cc#L184-L185
We need to expose this config on node.js client.
- The pulsar_client structure definition from the C++ client has been copied, allowing node.js client to set it using the C++ API instead of the C API.
- Expose `connectionTimeoutMs` configuration
> Support set connectionTimeout param

- src/ReaderConfig.cc
Fixes #415 
At my current employer, we have a centrally-managed Pulsar cluster that requires use of a pre-assigned `subscriptionRolePrefix` for your client when creating a reader.
As per docs, you should be able to do this with:
```
client.createReader({
topic,
startMessageId: Pulsar.MessageId.earliest(),
subscriptionRolePrefix: subscriptionPrefix,
});
```
However, this bug prevents that from working correctly.
Small change in `ReaderConfig.cc` to call the correct `PULSAR_PUBLIC` function.
This change is a trivial rework / code cleanup without any test coverage.  That said: I did test that, by using my patched client, I can create a reader in our internal setup described above.  (Without the patch, it fails.)
(Due to NDA, I can't describe that setup in more detail, sadly.)
(Your PR needs …
> [fix][client] handle subscriptionRolePrefix properly

- index.d.ts
- src/ConsumerConfig.cc
- tests/consumer.test.js
https://github.com/apache/pulsar-client-node/issues/408
- Support consumer key-shared policy
- Add testStickyConsumer to cover this.
- Other case covered by the CPP client.
> Support consumer key-shared policy

- src/Client.cc
- src/Client.h
When using the new async token‐supplier API (`() => Promise<string>`) introduced in https://github.com/apache/pulsar-client-node/pull/395, the JS `Authentication` object and its backing `ThreadSafeFunction` can be garbage‐collected if no live JS references remain. After the initial token expires, Pulsar’s broker will send a new auth challenge and the native code crashes when it tries to invoke a finalized TSFN.
By persisting a reference to the authentication object in the client it prevents the V8 garbage collector from dropping the token-supplier.
> [fix][client] prevent garbage collection of token-supplier

- .npmignore
exclude unnecessary files to be included in npm package
A small PR without linked to any issue
After I investigate the node_modules I get via npm install, I see some source files leakage as redundency to end user
Via this change, the folder `tests/` and `.github` will be exluded in next `npm publish` release
> [feat][npm publish]exclude unnecessary files to be included in npm package

- package-lock.json
The currently used version of `brace-expansion` contains the following vulnerability:
https://www.cve.org/CVERecord?id=CVE-2025-5889
Upgraded `brace-expansion` by running `npm audit fix`.
> Upgrade brace-expansion to address CVE-2025-5889

- .npmignore
The [1.14.0-rc.1](https://www.npmjs.com/package/pulsar-client/v/1.14.0-rc.1) has 427KB, it more than [v1.13.2](https://www.npmjs.com/package/pulsar-client/v/1.13.2)
- Ignore src/cert.pem
- Ignore .idea
> Ignore src/cert.pem

- index.d.ts
- src/ProducerConfig.cc
- tests/producer.test.js
Support set batchingMaxAllowedSizeInBytes on producer batch configuration
Support set batchingMaxAllowedSizeInBytes on producer batch configuration
- Added a test to verify it.
> Support set batchingMaxAllowedSizeInBytes on producer batch configuration
